[package]
name = "dyn-properties-derive"
version = "0.1.0"
edition = "2024"
description = "Derive macro for dyn-properties."
license = "MIT OR Apache-2.0"
repository = "https://github.com/bgallet/dyn-properties"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
humantime = "2"

[dev-dependencies]
quote = "1"
trybuild = "1"
