[package]
name = "dyn-properties"
version = "0.1.0"
edition = "2024"

[dependencies]
dyn-properties-derive = { path = "dyn-properties-derive", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
arc-swap = "1"
tokio = { version = "1", features = ["rt", "time", "fs"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "time"] }
tempfile = "3"
tracing-test = { version = "0.2", features = ["no-env-filter"] }

[workspace]
members = ["dyn-properties-derive"]
